"""How much of the benchmark rests on the 24 micrograph labels? Score with and without them.

The labels were assigned by a model from a 230x114 crop and its caption. They cannot be verified
here: the author is not a materials scientist, the captions state growth parameters rather than
morphology, and the crops are at the source figures' own resolution. So rather than assert them,
this measures what they carry — every scientific-evidence question whose answer comes from the
image is dropped, and every headline metric is recomputed.

  ./.venv/bin/python scripts/check_image_label_exposure.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from livelab.prompting import ARMS  # noqa: E402
from livelab.scoring import score_runs  # noqa: E402
from scripts.compare_arms import MODEL, VERSION, load_jsonl, reports  # noqa: E402

METRICS = ["Detection", "False alert", "Appropriate abstention", "Over-abstention",
           "Unsupported certainty"]


def main():
    index = json.load(open(ROOT / "data/replays/INDEX.json"))
    truth = lambda r: load_jsonl(ROOT / f"data/truth/{r}.jsonl")   # noqa: E731
    arms = [a for a in ("A", "C-context", "C-full") if (ROOT / "results" / MODEL / a / VERSION).exists()]
    common = [r for r in index if all(reports(a, r) for a in arms)]

    lines = ["# What the micrograph labels carry", "",
             "Generated by `scripts/check_image_label_exposure.py`. Every scientific-evidence",
             "question whose answer comes from the micrograph is dropped, and the headline metrics",
             "are recomputed. The labels were assigned by a model and are not independently",
             "verified; this says what would change if they were all wrong.", "",
             f"{len(common)} replays per arm.", "",
             "| Arm | Metric | As published | Without image-derived truth | Difference |",
             "| --- | --- | --- | --- | --- |"]
    worst = 0.0
    for a in arms:
        reps = {r: reports(a, r) for r in common}
        kw = dict(sees_images=ARMS[a]["images"])
        with_img = score_runs(reps, index, truth, **kw)
        without = score_runs(reps, index, truth, image_truth=False, **kw)
        for m in METRICS:
            b, n = with_img[m][0], without[m][0]
            worst = max(worst, abs(b - n))
            lines.append(f"| {a} | {m} | {b:.4f} | {n:.4f} | {abs(b - n):.4f} |")
    lines += ["", f"**Largest difference: {worst:.4f}.** Detection, false alert and appropriate",
              "abstention are identical to four decimals; the rest moves within rounding. No claim",
              "in the README rests on a label that could not be checked."]
    out = ROOT / "docs/results/image_label_exposure.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
