"""Compare arms from the archived logs in results/ and write docs/results/arm_comparison.md.

Every arm is scored with the same scorer and truth, on the replays complete in all compared arms.
Arms without images are scored against image-blind truth.
"""
import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from livelab.prompting import ARMS  # noqa: E402
from livelab.scoring import score_runs  # noqa: E402

MODEL, VERSION = "gemini-3.8-live", "prompt-v4"
PRIMARY = ["Detection", "False alert", "Attribution", "Appropriate abstention", "Over-abstention", "Unsupported certainty"]
SECONDARY = ["Negative called fault", "Obs. sensitivity", "Obs. invariance", "Action appropriate", "First action quality"]


def load_jsonl(p):
    return [json.loads(line) for line in open(p)]


def reports(arm, rid):
    p = ROOT / "results" / MODEL / arm / VERSION / f"{rid}__{arm}__s0.jsonl"
    if not p.exists():
        return None
    rows = load_jsonl(p)
    reps = [x["report_assessment"] for x in rows[1:] if x["event"] == "report"]
    return reps if len(reps) == 58 else None


def main():
    index = json.load(open(ROOT / "data/replays/INDEX.json"))
    arms = [a for a in ARMS if (ROOT / "results" / MODEL / a / VERSION).exists()]
    common = [r for r in index if all(reports(a, r) for a in arms)]
    truth = lambda r: load_jsonl(ROOT / f"data/truth/{r}.jsonl")
    cards, unknown = {}, {}
    for a in arms:
        reps = {r: reports(a, r) for r in common}
        cards[a] = score_runs(reps, index, truth, sees_images=ARMS[a]["images"])
        c = collections.Counter()
        for r in common:
            for t, x in zip(truth(r), reps[r]):
                if t["execution_state"] == "UNKNOWN":
                    c["should"] += 1
                    c[x["execution_state"]] += 1
        unknown[a] = c
    f = lambda v: "—" if v[0] != v[0] else f"{v[0]:.2f} [{v[1]:.2f}, {v[2]:.2f}]"
    lines = ["# Arm comparison", "",
             f"Generated by `scripts/compare_arms.py` from `results/{MODEL}/<arm>/{VERSION}/`, on the {len(common)} replays",
             "complete in every arm shown. One run per replay; 95% Wilson intervals. Arms without images are scored",
             "against image-blind truth.", "",
             "| Metric | " + " | ".join(arms) + " |", "| --- |" + " --- |" * len(arms)]
    for k in PRIMARY:
        lines.append(f"| **{k}** | " + " | ".join(f(cards[a][k]) for a in arms) + " |")
    for k in SECONDARY:
        lines.append(f"| {k} | " + " | ".join(f(cards[a][k]) for a in arms) + " |")
    lines.append("| Action latency (events) | " + " | ".join(f"{cards[a]['Action latency (events)']:.1f}" for a in arms) + " |")
    lines += ["", "Execution-state answers at events where the evidence supports only `UNKNOWN`:", "",
              "| Arm | events | UNKNOWN | NORMAL | ANOMALOUS |", "| --- | --- | --- | --- | --- |"]
    lines += [f"| {a} | {unknown[a]['should']} | {unknown[a]['UNKNOWN']} | {unknown[a]['NORMAL']} | {unknown[a]['ANOMALOUS']} |" for a in arms]
    out = ROOT / "docs/results/arm_comparison.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
