"""What the answers say on the items where the frames changed Opus 5's verdict.

Descriptive, run after the camera study was scored and before the follow-up was registered. It
reads the saved answers; it asks no model anything.

Written because a first reading of these answers was wrong. A keyword list that included "reflux"
and "condensate" counted 14 of 15 flipped answers as talking about the photographs, but both words
are also telemetry channels here. With words that can only mean the images, it is 1 of 15.

  ./.venv/bin/python scripts/explain_vision_flips.py [--model claude-opus-5]
"""
import argparse
import glob
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# Only words that can refer to the photographs. Not "reflux" or "condensate": both are channels.
IMAGE_WORDS = re.compile(r"photo|image|picture|camera|footage|video|visual|\bframes?\b|glass|coil",
                         re.I)
CHANNEL = "T701"


def verdict(record):
    return [c["args"] for c in record["calls"] if c["name"] == "report_assessment"][-1]


def text_of(record):
    return json.dumps(record["calls"], ensure_ascii=False) + " " + str(record.get("spoken") or "")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="claude-opus-5")
    args = ap.parse_args(argv)
    base = ROOT / "results/vision" / args.model
    registered = {i["item_id"] for i in json.load(open(ROOT / "data/vision/items.json"))["items"]}

    flips, frames_mention = [], 0
    for f in sorted(glob.glob(str(base / "frames" / "*.json"))):
        fr = json.loads(Path(f).read_text())
        tf = Path(f.replace("/frames/", "/telemetry/"))
        if fr["item_id"] not in registered or not tf.exists():
            continue
        te = json.loads(tf.read_text())
        frames_mention += bool(IMAGE_WORDS.search(text_of(fr)))
        before, after = verdict(te)["execution_state"], verdict(fr)["execution_state"]
        if after == "ANOMALOUS" and before != "ANOMALOUS":
            flips.append({"item_id": fr["item_id"], "condition": fr["condition"],
                          "before": before,
                          "mentions_images": bool(IMAGE_WORDS.search(text_of(fr))),
                          "cites_channel_with_frames": CHANNEL in text_of(fr),
                          "cites_channel_without": CHANNEL in text_of(te)})

    n = len(flips)
    lines = [f"# Where the frames changed {args.model}'s verdict", "",
             "Descriptive, from the saved answers of the [camera study](vision_results.md). "
             "Generated by `scripts/explain_vision_flips.py`.", "",
             "| | Items |", "| --- | --- |",
             f"| Verdicts changed to `ANOMALOUS` by adding the frames | {n} |",
             f"| ... whose answer mentions the photographs at all | "
             f"{sum(x['mentions_images'] for x in flips)} |",
             f"| ... whose answer cites `{CHANNEL}` (reboiler temperature) | "
             f"{sum(x['cites_channel_with_frames'] for x in flips)} |",
             f"| ... where the telemetry-only answer also cited `{CHANNEL}`, and did not call it "
             f"anomalous | {sum(x['cites_channel_without'] for x in flips)} |", "",
             f"Across all frames-arm answers, {frames_mention} mention the photographs.", "",
             "| Item | Condition | Without frames |", "| --- | --- | --- |"]
    lines += [f"| {x['item_id']} | {x['condition']} | {x['before']} |" for x in flips]

    out = ROOT / "docs/results/vision_flips.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
