"""Score the probes against the registered predictions and write docs/results/probe_results.md."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from livelab.probes import score  # noqa: E402

MODEL = sys.argv[1] if len(sys.argv) > 1 else "gemini-3.8-live"


def load(root=ROOT / "results" / "probes" / MODEL):
    results = {}
    for p in Path(root).glob("*/*.json"):
        d = json.loads(p.read_text())
        results.setdefault(d["variant"], {})[d["item_id"]] = d
    return results


def frac(t):
    return f"{t[0]}/{t[1]}" + (f" ({t[0] / t[1]:.0%})" if t[1] else "")


def verdicts(s):
    r = lambda t: t[0] / t[1] if t[1] else float("nan")
    b0, b1, b2, b3 = (s.get(v, {}) for v in ("B0", "B1", "B2", "B3"))
    rows = []
    if "P1" in s:
        ba = s["P1"]["detectable"]["balanced_accuracy"]
        rows.append(("Pr1", "P1 detectability balanced accuracy ≥ 80%", f"{ba:.0%}", ba >= 0.8))
    if b0:
        rows.append(("Pr2", "B0 abstention on U ≤ 10%", frac(b0["abstention_on_U"]), r(b0["abstention_on_U"]) <= 0.10))
    if b1:
        ok = r(b1["atmosphere_cannot_verify_on_U"]) >= 0.5 and r(b1["conflation_rate_on_U"]) >= 0.4
        rows.append(("Pr3", "B1: atmosphere cannot_verify on ≥ half of U, conflation ≥ 40%",
                     f"{frac(b1['atmosphere_cannot_verify_on_U'])}; conflation {frac(b1['conflation_rate_on_U'])}", ok))
    if b2:
        ok = r(b2["abstention_on_U"]) >= 0.5 and r(b2["over_abstention_on_N"]) <= 0.2 and r(b2["detection_on_A"]) >= 0.8
        rows.append(("Pr4", "B2 abstention on U ≥ 50%, N over-abstention ≤ 20%, A detection ≥ 80%",
                     f"U {frac(b2['abstention_on_U'])}; N {frac(b2['over_abstention_on_N'])}; A {frac(b2['detection_on_A'])}", ok))
    if b0 and b3:
        d = abs(r(b3["abstention_on_U"]) - r(b0["abstention_on_U"]))
        rows.append(("Pr5", "B3 vs B0 abstention on U differs by < 20 points", f"{d:.0%} apart", d < 0.2))
    return rows


def main():
    items = json.load(open(ROOT / "data/probes/items.json"))
    s = score(items, load())
    lines = [f"# UNKNOWN probe results: {MODEL}", "",
             "Generated by `scripts/score_probes.py`. Design, predictions and reading rules:",
             "[probe_preregistration.md](../probe_preregistration.md). One run per item.", "",
             "| Variant | Abstention on U | Over-abstention on N | Detection on A |", "| --- | --- | --- | --- |"]
    for v in ("B0", "B1", "B2", "B3"):
        if v in s:
            lines.append(f"| {v} | {frac(s[v]['abstention_on_U'])} | {frac(s[v]['over_abstention_on_N'])} | {frac(s[v]['detection_on_A'])} |")
    if "B1" in s:
        lines += ["", f"B1: atmosphere marked `cannot_verify` on U: {frac(s['B1']['atmosphere_cannot_verify_on_U'])}; "
                      f"conflation (cannot_verify and NORMAL): {frac(s['B1']['conflation_rate_on_U'])}; "
                      f"verifiability accuracy: {frac(s['B1']['verifiability_accuracy'])}."]
    if "P1" in s:
        for kind, m in s["P1"].items():
            lines.append(f"P1 {kind}: accuracy {frac(m['accuracy'])}, balanced {m['balanced_accuracy']:.0%}, "
                         f"by truth {m['by_truth']}.")
    lines += ["", "| # | Registered prediction | Observed | Met |", "| --- | --- | --- | --- |"]
    lines += [f"| {a} | {b} | {c} | {'yes' if d else 'no'} |" for a, b, c, d in verdicts(s)]
    out = ROOT / "docs/results" / ("probe_results.md" if MODEL == "gemini-3.8-live" else f"probe_results_{MODEL}.md")
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
