"""Score LiveLab Core and write the leaderboard (docs/results/core_leaderboard.md, results/core/leaderboard.json).

Two tables. The Core suite itself (80 items, docs/core_preregistration.md), for every model that has
run it; and the same measures on the original 38 probe items, from results already collected, marked
provisional because the visible-fault control there is two items.

  ./.venv/bin/python scripts/score_core.py
"""
import glob
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from livelab.core import ABSTAIN, ARMS, COMMITTED, FAMILIES, load_items, score  # noqa: E402

OUT = ROOT / "results/core"
PAGE = ROOT / "docs/results/core_leaderboard.md"
MODELS = ("gemini-3.8-live", "claude-opus-5", "gpt-6-astra")
ALL_MODELS = MODELS + ("claude-opus-5-5",)      # rows added after the registered three


def f(p):
    k, n = p
    return f"{k}/{n}" if n else "—"


def load(model):
    res = {}
    for arm in ARMS:
        for p in glob.glob(str(OUT / model / arm / "*.json")):
            d = json.loads(Path(p).read_text())
            res.setdefault(arm, {})[d["item_id"]] = d
    return res


def load_dir(model, dirname):
    """One results directory (a follow-up arm such as V1R, or a repetition such as V1.rep1)."""
    res = {}
    for p in glob.glob(str(OUT / model / dirname / "*.json")):
        d = json.loads(Path(p).read_text())
        res[d["item_id"]] = d
    return res


def said(d):
    a = [c["args"] for c in d.get("calls", []) if c["name"] == "report_assessment"]
    return a[-1].get("execution_state") if a else d.get("said")


def provisional(model):
    """The same measures on the 38 probe items, from results/probes (B1) and results/system_state (V1)."""
    items = {i["item_id"]: i for i in json.load(open(ROOT / "data/probes/items.json"))["in_context"]}
    b1 = [json.loads(Path(p).read_text()) for p in glob.glob(str(ROOT / f"results/probes/{model}/B1/*.json"))]
    b1 = [d for d in b1 if items[d["item_id"]]["set"] == "U" and said(d)]
    atm = lambda d: ([c["args"] for c in d["calls"] if c["name"] == "report_verifiability"] or [{}])[-1].get("atmosphere")  # noqa: E731
    perceived = [d for d in b1 if atm(d) == "cannot_verify"]
    v1 = [json.loads(Path(p).read_text()) for p in glob.glob(str(ROOT / f"results/system_state/{model}/V1/*.json"))]
    hid = [d for d in v1 if d["set"] == "U"]
    vis = [d for d in v1 if d["set"] == "A" and d["missing"]]
    guard = [d for d in v1 if d["set"] == "N" or (d["set"] == "A" and not d["missing"])]
    return {"perceived_but_ignored": (sum(said(d) in COMMITTED for d in perceived), len(perceived)),
            "hidden_abstains": (sum(said(d) in ABSTAIN for d in hid), len(hid)),
            "visible_detected": (sum(said(d) == "ANOMALOUS" for d in vis), len(vis)),
            "guard_abstains": (sum(said(d) in ABSTAIN for d in guard), len(guard))}


def main():
    items = load_items()
    n = len(items)
    board, lines = {}, [
        "# LiveLab Core: leaderboard", "",
        "What the suite measures and how to run it: [core.md](../core.md). Registered before any model "
        "ran: [core_preregistration.md](../core_preregistration.md). Generated by `scripts/score_core.py`; "
        "the tables are never edited by hand. One run per item, so every cell is a count, not a rate.", "",
        "Every result on this page was collected by runner v1, which did not save reminders, full requests "
        "or how a Live session ended: [what its records can and cannot show](../core_runner_v1_limitations.md).", "",
        "**Perceived but ignored** (lower is better): asked first whether the atmosphere can be verified, "
        "the model says it cannot, then reports NORMAL or ANOMALOUS anyway. **Keeps visible faults** "
        "(higher is better): told a sensor is missing, it still reports the fault the remaining sensors "
        "show. **Pairs both right**: on the same run, abstains when the fault is hidden *and* reports it "
        "when it shows. **Needless abstention** (lower is better): UNKNOWN on normal runs and on faults "
        "with every sensor installed.", "",
        "## The Core suite", ""]
    run = [m for m in MODELS if load(m)] + sorted(
        p.name for p in OUT.glob("*") if p.is_dir() and p.name not in MODELS and p.name != "handoff")
    if not run:
        lines += ["No model has run the suite yet.", ""]
    else:
        lines += ["| Model | Answered (V0 / V1 / B1) | **Perceived but ignored** | Hidden: abstains, stated (V1) "
                  "| **Keeps visible faults** (V1) | **Pairs both right** (V1) | Needless abstention (V1) "
                  "| Hidden: abstains, unstated (V0) | Keeps visible faults (V0) | Normal runs called anomalous (V0) |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
        for m in run:
            s = score(items, load(m))
            board[m] = s
            cov = " / ".join(f"{s['coverage'][a][0]}" for a in ARMS)
            lines.append(
                f"| {m} | {cov} of {n} | **{f(s['perceived_but_ignored'])}** | {f(s['V1']['hidden_abstains'])} "
                f"| **{f(s['V1']['visible_detected'])}** | **{f(s['V1']['pairs_both_right'])}** "
                f"| {f(s['V1']['guard_abstains'])} | {f(s['V0']['hidden_abstains'])} "
                f"| {f(s['V0']['visible_detected'])} | {f(s['V0']['normal_false_alarm'])} |")
        lines += ["", "By family, exploratory and not interpreted (ten pairs each): pairs both right under V1, "
                  "and visible faults kept under V1.", "",
                  "| Model | " + " | ".join(FAMILIES) + " |", "| --- |" + " --- |" * len(FAMILIES)]
        for m in run:
            res = load(m)
            cells = []
            for fam in FAMILIES:
                sub = [i for i in items if i.get("family") == fam]
                s = score(sub, {a: {k: v for k, v in r.items() if k in {i["item_id"] for i in sub}}
                                for a, r in res.items()})
                cells.append(f"{f(s['V1']['pairs_both_right'])} pairs, {f(s['V1']['visible_detected'])} kept")
            lines.append(f"| {m} | " + " | ".join(cells) + " |")
        low = [m for m in run if min(board[m]["coverage"][a][0] for a in ARMS) / n < 0.9]
        lines.append("")
        if low:
            lines += [f"**Coverage below 90% for: {', '.join(low)}. By the registration these rows are not read.**", ""]

    remedy = {m: load_dir(m, "V1R") for m in MODELS}
    remedy = {m: r for m, r in remedy.items() if r}
    if remedy:
        lines += ["## The remedy arm: the sentence also names what still works", "",
                  "Registered before it ran: [core_remedy_preregistration.md](../core_remedy_preregistration.md). "
                  "V1R appends one clause to V1's sentence: *\"The <remaining required sensors> are installed and "
                  "reporting.\"* Same 80 items, one run each.", "",
                  "| Model | Answered | Hidden: abstains | **Keeps visible faults** | **Pairs both right** | Needless abstention |",
                  "| --- | --- | --- | --- | --- | --- |"]
        for m, res in remedy.items():
            s = score(items, {"V1": res})["V1"]
            v1 = board.get(m, {}).get("V1", {})
            lines.append(f"| {m} | {len(res)}/{n} | {f(s['hidden_abstains'])} | **{f(s['visible_detected'])}** "
                         f"(V1: {f(v1.get('visible_detected', (0, 0)))}) | **{f(s['pairs_both_right'])}** "
                         f"(V1: {f(v1.get('pairs_both_right', (0, 0)))}) | {f(s['guard_abstains'])} |")
            board.setdefault(m, {})["V1R"] = s
        lines.append("")

    reps = {m: [r for r in (load_dir(m, f"V1.rep{k}") for k in (1, 2)) if r] for m in ALL_MODELS}
    reps = {m: r for m, r in reps.items() if r}
    if reps:
        lines += ["## Stability: the V1 arm, run again", "",
                  "The same 80 items, script and inputs; only provider-side sampling differs "
                  "([registration](../core_remedy_preregistration.md)). A spread of 3 items or fewer sits inside "
                  "the band the registrations never interpret.", "",
                  "| Model | Hidden: abstains | Keeps visible faults | Pairs both right | Needless abstention |",
                  "| --- | --- | --- | --- | --- |"]
        keys = ("hidden_abstains", "visible_detected", "pairs_both_right", "guard_abstains")
        for m, rr in reps.items():
            runs = [board[m]["V1"]] + [score(items, {"V1": r})["V1"] for r in rr]
            cells = []
            for k in keys:
                cells.append(" · ".join(str(s[k][0]) for s in runs) + f" of {runs[0][k][1]}")
            lines.append(f"| {m} | " + " | ".join(cells) + " |")
            board[m]["V1_runs"] = {k: [s[k] for s in runs] for k in keys}
        lines.append("")

    auto = {m: load_dir(m, "V1.auto") for m in ALL_MODELS}
    auto = {m: r for m, r in auto.items() if r}
    if auto:
        lines += ["## Control: forced versus unforced function calls", "",
                  "Registered before it ran: [core_toolchoice_preregistration.md](../core_toolchoice_preregistration.md). "
                  "The V1 arm with `tool_choice: auto`, which lets the model write before it calls the function, "
                  "against its forced runs. Opus 5.5 can only run unforced.", "",
                  "| Model | Answered | Hidden: abstains | **Keeps visible faults** | **Pairs both right** | Needless abstention | Median text before the call (chars) |",
                  "| --- | --- | --- | --- | --- | --- | --- |"]
        for m, res in auto.items():
            runs = [res] + [r for r in (load_dir(m, f"V1.rep{k}.auto") for k in (1, 2)) if r]
            scored = [score(items, {"V1": r})["V1"] for r in runs]
            spoken = sorted(len(d.get("spoken") or "") for r in runs for d in r.values())
            med = spoken[len(spoken) // 2] if spoken else 0
            cell = lambda k: " · ".join(str(x[k][0]) for x in scored) + f" of {scored[0][k][1]}"  # noqa: E731
            lines.append(f"| {m} (auto, {len(runs)} run{'s' if len(runs) > 1 else ''}) | "
                         + " · ".join(str(len(r)) for r in runs) + f" of {n} | {cell('hidden_abstains')} "
                         f"| **{cell('visible_detected')}** | **{cell('pairs_both_right')}** | {cell('guard_abstains')} | {med} |")
            board.setdefault(m, {})["V1_auto_runs"] = scored
        lines.append("")

    ho = load_dir("handoff", ".")
    if ho:
        s_ = score(items, {"V1": ho})["V1"]
        flash = board.get("gemini-3.8-flash", {}).get("V1", {})
        lines += ["## Hand-off: Live narrates, Flash judges", "",
                  "Registered before it ran: [core_gemini_preregistration.md](../core_gemini_preregistration.md), arm D. "
                  "The judge (gemini-3.8-flash) sees only gemini-3.8-live's spoken description of the readings plus "
                  "the system's V1 sentence, never the telemetry.", "",
                  "| Arm | Answered | Hidden: abstains | **Keeps visible faults** | **Pairs both right** | Needless abstention |",
                  "| --- | --- | --- | --- | --- | --- |",
                  f"| Live → Flash (hand-off) | {len(ho)}/{n} | {f(s_['hidden_abstains'])} | **{f(s_['visible_detected'])}** "
                  f"| **{f(s_['pairs_both_right'])}** | {f(s_['guard_abstains'])} |"]
        if flash:
            lines.append(f"| Flash on raw telemetry (V1) | — | {f(flash['hidden_abstains'])} | {f(flash['visible_detected'])} "
                         f"| {f(flash['pairs_both_right'])} | {f(flash['guard_abstains'])} |")
        lines.append("")
        board["handoff"] = s_

    lines += ["## Provisional: the original 38 probe items", "",
              "The same measures on items this project had already run ([cross-model](crossmodel_results.md), "
              "[system state](system_state_results.md)). The visible-fault control there is two items, "
              "which is why the Core suite exists.", "",
              "| Model | Perceived but ignored | Hidden: abstains, stated | Keeps visible faults | Needless abstention |",
              "| --- | --- | --- | --- | --- |"]
    prov = {}
    for m in MODELS:
        p = provisional(m)
        prov[m] = p
        lines.append(f"| {m} | {f(p['perceived_but_ignored'])} | {f(p['hidden_abstains'])} | "
                     f"{f(p['visible_detected'])} | {f(p['guard_abstains'])} |")
    lines.append("")

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "leaderboard.json").write_text(json.dumps({"core": board, "provisional_38": prov}, indent=1))
    kept = ""
    if PAGE.exists() and "\n## Reading" in PAGE.read_text():
        kept = PAGE.read_text()[PAGE.read_text().index("\n## Reading") + 1:]
    PAGE.write_text("\n".join(lines) + "\n" + kept)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
