"""Score the specialist study against Ps1–Ps4 (docs/specialist_preregistration.md).

  ./.venv/bin/python scripts/score_specialist.py
"""
import glob
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "results/specialist"
MODELS = ("claude-opus-5", "gemini-3.8-live")
PRICE = {"claude-opus-5": (5.0, 25.0)}          # USD per 1M input, output tokens


def stats(pred, items):
    """pred: item_id -> verdict."""
    got = [(it, pred.get(it["item_id"])) for it in items]
    right = [it for it, v in got if v == it["truth"]]
    flip = {}
    for it, v in got:
        if it["set"] == "flip":
            flip.setdefault(it["group"], []).append(v == it["truth"])
    return {"acc": len(right), "unknown": sum(v == "UNKNOWN" for _, v in got),
            "pairs": sum(1 for it in right if it["set"] == "pair"),
            "flips": sum(1 for it in right if it["set"] == "flip"),
            "both": sum(len(x) == 2 and all(x) for x in flip.values())}


def cost(model, rows):
    if model not in PRICE:
        return None
    i = sum((r.get("usage") or {}).get("prompt_token_count", 0) for r in rows)
    o = sum((r.get("usage") or {}).get("response_token_count", 0) for r in rows)
    return (i * PRICE[model][0] + o * PRICE[model][1]) / 1e6 / max(len(rows), 1)


def main():
    items = json.load(open(ROOT / "data/pdms_pilot/items.json"))["items"]
    rep = json.load(open(SPEC / "report.json"))
    rows = []
    for m in MODELS:
        n = [json.load(open(f)) for f in glob.glob(str(ROOT / f"results/pilot1/{m}/C1/*.json"))]
        rows.append((f"N: {m}, sees the photograph", stats({r["item_id"]: r["verdict"] for r in n}, items),
                     cost(m, n)))
    for name, label in (("primary", "S: specialist (near-duplicates at 0.97 excluded)"),
                        ("strict", "S: specialist (near-duplicates at 0.90 excluded)")):
        s = json.load(open(SPEC / f"S_{name}.json"))
        rows.append((label, stats({k: v["verdict"] for k, v in s.items()}, items), 0.0))
    for m in MODELS:
        sl = [json.load(open(f)) for f in glob.glob(str(SPEC / f"SL/{m}/*.json"))]
        rows.append((f"S+L: {m}, sees S's verdict", stats({r["item_id"]: r["verdict"] for r in sl}, items),
                     cost(m, sl)))

    lines = ["# Native multimodal against a specialist vision pipeline", "",
             "Registered before the specialist was built: [specialist_preregistration.md]"
             "(../specialist_preregistration.md). Generated by `scripts/score_specialist.py`. "
             "The same 100 PDMS inspections as pilot 1: 60 in matched pairs, 40 on 20 images asked "
             "under two steps.", "",
             "| Arm | Right of 100 | UNKNOWN | Pairs (of 60) | Flip items (of 40) | Flip images both right (of 20) | API cost per inspection |",
             "| --- | --- | --- | --- | --- | --- | --- |"]
    for label, s, c in rows:
        cs = "—" if c is None else ("≈ $0 (local)" if c == 0 else f"${c:.4f}")
        lines.append(f"| {label} | **{s['acc']}** | {s['unknown']} | {s['pairs']} | {s['flips']} | "
                     f"{s['both']} | {cs} |")
    p, st = rep["primary"], rep["strict"]
    lines += ["", f"S trains on {p['training_annotations']:,} annotations after removing the 80 test "
              f"images and {p['near_duplicate_images_excluded']} near-duplicate images "
              f"({st['training_annotations']:,} and {st['near_duplicate_images_excluded']} at the "
              f"stricter threshold). On this machine's CPU it takes "
              f"{rep['embedding_ms_per_image']:.0f} ms to embed an image and "
              f"{p['classify_ms_per_item']:.2f} ms to classify it.", "",
              "| S trained on | Annotations | Right of 100 | UNKNOWN |", "| --- | --- | --- | --- |"]
    for k in ("train10", "train25", "train50", "primary"):
        r = rep[k]
        lines.append(f"| {'all' if k == 'primary' else k[5:] + '%'} | {r['training_annotations']:,} | "
                     f"{r['accuracy']} | {r['unknown']} |")

    n_best = max(rows[0][1]["acc"], rows[1][1]["acc"])
    gem_both = rows[1][1]["both"]
    s_acc, s_both = rows[2][1]["acc"], rows[2][1]["both"]
    sl = [rows[4][1]["acc"], rows[5][1]["acc"]]
    lines += ["", "## The registered predictions", "",
              "| # | Prediction | Observed | Met |", "| --- | --- | --- | --- |",
              f"| Ps1 | S at least as accurate as the better N model ({n_best}) | {s_acc} | "
              f"{'yes' if s_acc >= n_best else '**no**'} |",
              f"| Ps2 | At 10% of training data S falls below 74 | {rep['train10']['accuracy']} | "
              f"{'yes' if rep['train10']['accuracy'] < 74 else '**no**'} |",
              f"| Ps3 | S+L within 5 points of S, both models | {sl[0]} and {sl[1]} against {s_acc} | "
              f"{'yes' if all(abs(x - s_acc) <= 5 for x in sl) else '**no**'} |",
              f"| Ps4 | S both-steps-right on flip images at least Gemini's ({gem_both}) | {s_both} | "
              f"{'yes' if s_both >= gem_both else '**no**'} |", ""]

    out = ROOT / "docs/results/specialist_results.md"
    kept = ""
    if out.exists() and "\n## Reading" in out.read_text():
        kept = out.read_text()[out.read_text().index("\n## Reading") + 1:]
    out.write_text("\n".join(lines) + "\n" + kept)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
