"""Run every mock observer over every frozen replay and print the scorecard.

This validates the metrics before any real model is called: the oracle must score perfectly,
and each degenerate mock must be caught by the metric designed to catch it.
"""
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from livelab.mock_models import MOCKS  # noqa: E402
from livelab.scoring import observability_pairs, score_replay, summarize  # noqa: E402

ROWS = ["Detection", "False alert", "Negative called fault", "Attribution", "Appropriate abstention",
        "Over-abstention", "Unsupported certainty", "Obs. sensitivity", "Obs. invariance", "Action appropriate", "First action quality"]


def load_jsonl(path):
    return [json.loads(line) for line in open(path)]


def run_all():
    index = json.load(open(ROOT / "data/replays/INDEX.json"))
    results = {}
    for mock in MOCKS:
        counts, by_ep = [], {}
        for rid, meta in index.items():
            events = load_jsonl(ROOT / f"data/replays/{rid}.jsonl")
            truth = load_jsonl(ROOT / f"data/truth/{rid}.jsonl")
            reports = mock.run(events, truth)
            counts.append(score_replay(truth, reports))
            by_ep.setdefault(meta["episode_id"], {})[meta["condition"]] = (truth, reports)
        for conds in by_ep.values():
            for cond, (t, r) in conds.items():
                if cond != "base" and "base" in conds:
                    counts.append(observability_pairs(*conds["base"], t, r))
        results[mock.name] = summarize(counts)
    return results


def fmt(v):
    if isinstance(v, tuple) and len(v) == 3:
        return "  —  " if math.isnan(v[0]) else f"{v[0]:.2f}"
    return str(v)


def main():
    results = run_all()
    names = list(results)
    lines = ["# Mock scorecard", "",
             "Generated by `scripts/score_mocks.py` over every frozen replay in `data/replays/`. These are",
             "mock observers, not models: the table checks that each metric catches the failure it was built",
             "to catch before any real model is run. Two mocks read the image's manifest label as a stand-in",
             "for perfect vision.", "",
             "| Metric | " + " | ".join(f"`{n}`" for n in names) + " |",
             "| --- |" + " --- |" * len(names)]
    lines += [f"| {row} | " + " | ".join(fmt(results[n][row]).strip() for n in names) + " |" for row in ROWS]
    out = ROOT / "docs/results/mock_scorecard.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
