"""Score the real-plant study under both legends, side by side, and judge Pv1–Pv4.

Written before any item ran under the corrected legend (docs/realdata_v2_preregistration.md).

  ./.venv/bin/python scripts/score_realdata.py
"""
import glob
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODELS = ("gemini-3.8-live", "claude-opus-5", "gpt-6-astra")
LEGENDS = {"v1": "realdata", "v2": "realdata_v2"}
ABSTAIN = {"UNKNOWN", "CANNOT_VERIFY"}
HEATER = re.compile(r"\bT70[12468]\b")
COVERAGE = 0.90
N_ITEMS = 99


def load(results_dir, model):
    out = {}
    for f in glob.glob(str(ROOT / "results" / results_dir / model / "*.json")):
        d = json.loads(Path(f).read_text())
        a = [c["args"] for c in d["calls"] if c["name"] == "report_assessment"]
        if a and a[-1].get("execution_state"):
            out[Path(f).stem] = d | {"said": a[-1]["execution_state"],
                                     "cites_heater": bool(HEATER.search(
                                         json.dumps(a[-1].get("evidence"))))}
    return out


def frac(k, n):
    return f"{k}/{n} ({k / n:.0%})" if n else "—"


def main():
    rows = {(m, lg): load(d, m) for m in MODELS for lg, d in LEGENDS.items()}
    lines = ["# The real-plant study under both legends", "",
             "Registered before the rerun: [realdata_v2_preregistration.md]"
             "(../realdata_v2_preregistration.md). Generated by `scripts/score_realdata.py`, "
             "written before the rerun. V1 is the original, wrong instrument legend; V2 is the "
             "corrected one. Same 99 items, same everything else.", "",
             "| Model | Legend | Answered | Detection on Full | **Abstention on Blind** | "
             "False alert on Control | Control false alerts citing a heater |",
             "| --- | --- | --- | --- | --- | --- | --- |"]
    stat = {}
    for m in MODELS:
        for lg in LEGENDS:
            r = rows[(m, lg)]
            by = {c: [x for x in r.values() if x["condition"] == c]
                  for c in ("full", "blind", "control")}
            det = sum(x["said"] == "ANOMALOUS" for x in by["full"])
            ab = sum(x["said"] in ABSTAIN for x in by["blind"])
            fa = [x for x in by["control"] if x["said"] == "ANOMALOUS"]
            heat = sum(x["cites_heater"] for x in fa)
            stat[(m, lg)] = {"n": len(r), "ab": ab, "nb": len(by["blind"]), "fa": len(fa),
                             "nc": len(by["control"]), "heat": heat}
            lines.append(f"| {m} | {lg} | {len(r)}/{N_ITEMS} | {frac(det, len(by['full']))} | "
                         f"{frac(ab, len(by['blind']))} | {frac(len(fa), len(by['control']))} | "
                         f"{heat}/{len(fa)} |")
    lines.append("")
    low = [m for m in MODELS if stat[(m, "v2")]["n"] / N_ITEMS < COVERAGE]
    if low:
        lines += [f"**Coverage below {COVERAGE:.0%} under V2 for: {', '.join(low)}. "
                  "By the registration these are not read.**", ""]

    v = lambda m, k: stat[(m, "v2")][k]           # noqa: E731
    o = lambda m, k: stat[(m, "v1")][k]           # noqa: E731
    lines += ["## The registered predictions", "",
              "| # | Prediction | Observed | Met |", "| --- | --- | --- | --- |"]
    for m in MODELS:
        rate = v(m, "ab") / v(m, "nb") if v(m, "nb") else 0
        lines.append(f"| Pv1 | blind abstention ≤ 10% ({m}) | {frac(v(m, 'ab'), v(m, 'nb'))} | "
                     f"{'yes' if rate <= 0.10 else '**no**'} |")
    for m in ("claude-opus-5", "gpt-6-astra"):
        drop = o(m, "fa") - v(m, "fa")
        lines.append(f"| Pv2 | control false alerts fall by ≥ 5 items ({m}) | "
                     f"{o(m, 'fa')} → {v(m, 'fa')} | {'yes' if drop >= 5 else '**no**'} |")
    g = "gemini-3.8-live"
    lines.append(f"| Pv3 | Gemini's control false alerts move < 3 items | {o(g, 'fa')} → "
                 f"{v(g, 'fa')} | {'yes' if abs(o(g, 'fa') - v(g, 'fa')) < 3 else '**no**'} |")
    for m in ("claude-opus-5", "gpt-6-astra"):
        ok = v(m, "fa") == 0 or v(m, "heat") < v(m, "fa") / 2
        lines.append(f"| Pv4 | fewer than half of remaining control false alerts cite a heater "
                     f"({m}) | {v(m, 'heat')}/{v(m, 'fa')} | {'yes' if ok else '**no**'} |")
    lines.append("")

    out = ROOT / "docs/results/realdata_v2_results.md"
    kept = ""
    if out.exists() and "\n## Reading" in out.read_text():
        kept = out.read_text()[out.read_text().index("\n## Reading") + 1:]
    out.write_text("\n".join(lines) + "\n" + kept)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
