"""Score pilot 1 against Pa1–Pa4 (docs/pilots_preregistration.md). Written before any model ran.

  ./.venv/bin/python scripts/score_pdms_pilot.py
"""
import glob
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "results/pilot1"
CONDS = ("C0", "C1", "C2")
MODELS = ("claude-opus-5", "gemini-3.8-live")


def load(model, cond):
    return {json.loads(Path(f).read_text())["item_id"]: json.loads(Path(f).read_text())
            for f in glob.glob(str(OUT / model / cond / "*.json"))}


def pct(k, n):
    return f"{k}/{n} ({k / n:.0%})" if n else "—"


def main():
    items = json.load(open(OUT / "items.json"))["items"]
    ids = [it["item_id"] for it in items]
    descs = [json.loads(Path(f).read_text()) for f in glob.glob(str(OUT / "descriptions/*.json"))]
    dropped = sum(d["text"] is None for d in descs)

    lines = ["# Pilot 1: does a model join what it sees to the task step?", "",
             "Registered before items were chosen: [pilots_preregistration.md]"
             "(../pilots_preregistration.md). Generated by `scripts/score_pdms_pilot.py`, written "
             "before any model ran. PDMS stills (Lin et al., CC BY 4.0). 100 items on 80 images: "
             "30 matched normal/abnormal pairs, and 20 images asked under two task steps whose "
             "labels differ.", "",
             f"Visual-fact descriptions: {len(descs)} written, {dropped} dropped for banned words.",
             ""]
    stat = {}
    for m in MODELS:
        r = {c: load(m, c) for c in CONDS}
        if not any(r.values()):
            continue
        lines += [f"## {m}", "",
                  "| | Answered | Accuracy | UNKNOWN | Accuracy, pairs | Accuracy, flip items |",
                  "| --- | --- | --- | --- | --- | --- |"]
        for c in CONDS:
            got = [r[c][i] for i in ids if i in r[c]]
            right = [x for x in got if x["verdict"] == x["truth"]]
            unk = sum(x["verdict"] == "UNKNOWN" for x in got)
            pr = [x for x in got if x["set"] == "pair"]
            fl = [x for x in got if x["set"] == "flip"]
            # both steps right on a flip image
            groups = {}
            for x in fl:
                groups.setdefault(x["group"], []).append(x["verdict"] == x["truth"])
            both = sum(len(v) == 2 and all(v) for v in groups.values())
            stat[(m, c)] = {"n": len(got), "acc": len(right) / len(got) if got else 0,
                            "both": both, "nflip": sum(len(v) == 2 for v in groups.values())}
            lines.append(f"| {c} | {len(got)}/{len(ids)} | {pct(len(right), len(got))} | "
                         f"{pct(unk, len(got))} | "
                         f"{pct(sum(x['verdict'] == x['truth'] for x in pr), len(pr))} | "
                         f"{pct(sum(x['verdict'] == x['truth'] for x in fl), len(fl))} |")
        s1 = stat.get((m, "C1"), {})
        lines += ["", f"Flip images with **both** steps right: " + ", ".join(
            f"{c} {stat[(m, c)]['both']}/{stat[(m, c)]['nflip']}" for c in CONDS if (m, c) in stat)
            + ".", ""]

    lines += ["## The registered predictions", "",
              "| # | Prediction | Observed | Met |", "| --- | --- | --- | --- |"]
    for m in MODELS:
        if (m, "C0") not in stat:
            continue
        a0, a1, a2 = (stat[(m, c)]["acc"] * 100 for c in CONDS)
        s1 = stat[(m, "C1")]
        both = s1["both"] / s1["nflip"] * 100 if s1["nflip"] else 0
        lines += [
            f"| Pa1 | C0 accuracy below 70% ({m}) | {a0:.0f}% | {'yes' if a0 < 70 else '**no**'} |",
            f"| Pa2 | C1 beats C0 by at least 15 points ({m}) | {a1 - a0:+.0f} points | "
            f"{'yes' if a1 - a0 >= 15 else '**no**'} |",
            f"| Pa3 | C2 at least as accurate as C1, within 5 points ({m}) | "
            f"{a2 - a1:+.0f} points | {'yes' if a2 - a1 >= -5 else '**no**'} |",
            f"| Pa4 | both steps right on flip images under C1 below 60% ({m}) | "
            f"{s1['both']}/{s1['nflip']} ({both:.0f}%) | {'yes' if both < 60 else '**no**'} |"]
    lines.append("")

    out = ROOT / "docs/results/pilot1_results.md"
    kept = ""
    if out.exists() and "\n## Reading" in out.read_text():
        kept = out.read_text()[out.read_text().index("\n## Reading") + 1:]
    out.write_text("\n".join(lines) + "\n" + kept)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
