"""Score the camera-compensation study against its registered predictions.

Written before the first item was run, so the reading rules could not be shaped by the numbers.

  ./.venv/bin/python scripts/score_vision.py
"""
import glob
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

ABSTAIN = {"UNKNOWN", "CANNOT_VERIFY"}
ARMS = ("telemetry", "frames")
MARGIN = 10          # points; the registration's bar for Pr1 and Pr2
COVERAGE = 0.90      # below this an arm is not read, as everywhere in this project


def load(model, arm):
    """item_id -> the state the model reported, for items that came back with an answer."""
    out = {}
    for f in glob.glob(str(ROOT / "results/vision" / model / arm / "*.json")):
        d = json.loads(Path(f).read_text())
        a = [c["args"] for c in d["calls"] if c["name"] == "report_assessment"]
        if a and a[-1].get("execution_state"):
            out[d["item_id"]] = d | {"said": a[-1]["execution_state"]}
    return out


def pct(hit, n):
    return f"{hit}/{n} ({hit / n:.0%})" if n else "—"


def points(hit, n):
    return 100.0 * hit / n if n else 0.0


def main():
    root = ROOT / "results/vision"
    # a model is a folder holding the two arms; frames_arrived/ beside them is gate evidence
    models = sorted(p.name for p in root.glob("*")
                    if all((p / a).is_dir() for a in ARMS)) if root.exists() else []
    if not models:
        sys.exit("nothing to score yet: run scripts/run_vision.py first")
    registered = {it["item_id"]: it
                  for it in json.load(open(ROOT / "data/vision/items.json"))["items"]}

    lines = ["# Does a camera put a missing instrument back?", "",
             "> **Correction (2026-09-21).** Every item here was sent with a wrong plant description "
             "(five heater temperatures described as column temperatures; [deviation 5](../realdata_preregistration.md)). "
             "Each false alert on a fault-free run cites one of those heaters, `T701`. "
             "The arms all received the same description, so the comparisons between arms "
             "hold; the absolute false-alert rates do not measure the plant.", "",
             "Registered before any frame was extracted: "
             "[vision_preregistration.md](../vision_preregistration.md). Generated by "
             "`scripts/score_vision.py`, which was written before the first item ran.", "",
             "Each item is run twice and is its own control: the same telemetry window with the "
             "observing instrument group removed, then that same text plus six photographs from "
             "the plant's own camera across the same window.", ""]

    verdicts = []
    for model in models:
        # Only items in the current item set: a result left over from an item that was later
        # dropped (deviation 5) must not be scored as if it were still part of the study.
        arms = {a: {i: r for i, r in load(model, a).items() if i in registered} for a in ARMS}
        paired = sorted(set(arms["telemetry"]) & set(arms["frames"]))
        lines += [f"## {model}", "",
                  "| Arm | Answered | Coverage |", "| --- | --- | --- |"]
        for a in ARMS:
            lines.append(f"| {a} | {len(arms[a])}/{len(registered)} | "
                         f"{len(arms[a]) / len(registered):.0%} |")
        lines += ["", f"**{len(paired)} items answered in both arms**; everything below is scored "
                      "on those, so no difference comes from a missing run.", ""]

        under = [a for a in ARMS if len(arms[a]) / max(len(registered), 1) < COVERAGE]
        if under:
            lines += [f"**Coverage below {COVERAGE:.0%} in: {', '.join(under)}. "
                      "By the registration this is not read.**", ""]

        cell = {}
        for cond, name in (("blind", "Detection on blind (ANOMALOUS)"),
                           ("control", "False alert on control (ANOMALOUS)")):
            ids = [i for i in paired if arms["telemetry"][i]["condition"] == cond]
            for a in ARMS:
                cell[(cond, a)] = (sum(arms[a][i]["said"] == "ANOMALOUS" for i in ids), len(ids))
            cell[(cond, "ids")] = ids
            cell[(cond, "name")] = name
        for cond in ("blind", "control"):
            ids = cell[(cond, "ids")]
            for a in ARMS:
                cell[(cond, "ab", a)] = (sum(arms[a][i]["said"] in ABSTAIN for i in ids), len(ids))

        lines += ["| Measure | telemetry | + frames | Difference |", "| --- | --- | --- | --- |"]
        for cond in ("blind", "control"):
            t, f = cell[(cond, "telemetry")], cell[(cond, "frames")]
            d = points(*f) - points(*t)
            lines.append(f"| {cell[(cond, 'name')]} | {pct(*t)} | {pct(*f)} | "
                         f"{d:+.0f} points |")
        for cond in ("blind", "control"):
            t, f = cell[(cond, "ab", "telemetry")], cell[(cond, "ab", "frames")]
            lines.append(f"| Abstention on {cond} | {pct(*t)} | {pct(*f)} | "
                         f"{points(*f) - points(*t):+.0f} points |")
        lines.append("")

        # Which items actually moved, in each direction. A net of zero can hide two changes.
        for cond in ("blind", "control"):
            ids = cell[(cond, "ids")]
            moved = [(arms["telemetry"][i]["said"], arms["frames"][i]["said"]) for i in ids]
            gained = [1 for before, after in moved
                      if after == "ANOMALOUS" and before != "ANOMALOUS"]
            lost = [1 for before, after in moved
                    if before == "ANOMALOUS" and after != "ANOMALOUS"]
            lines.append(f"On {cond}, the frames changed the verdict to ANOMALOUS on "
                         f"{len(gained)} items and away from it on {len(lost)}.")
        lines.append("")

        blind_ids = cell[("blind", "ids")]
        groups = sorted({registered[i].get("removed_group") for i in blind_ids} - {None})
        if groups:
            lines += ["### By removed instrument group", "",
                      "**Exploratory, and not interpreted** — the registration fixed that before "
                      "any run, because these cells hold a handful of items each.", "",
                      "| Removed | n | telemetry | + frames |", "| --- | --- | --- | --- |"]
            for g in groups:
                ids = [i for i in blind_ids if registered[i].get("removed_group") == g]
                lines.append(f"| {g} | {len(ids)} | "
                             + " | ".join(pct(sum(arms[a][i]["said"] == "ANOMALOUS" for i in ids),
                                              len(ids)) for a in ARMS) + " |")
            lines.append("")

        short = [i for i in paired if (registered[i].get("frame_span_s") or 0) < 1200]
        if short:
            lines += [f"{len(short)} of these items have frames over less than the full 20 "
                      "minutes, because the camera was switched on late "
                      "(deviation 1 of the registration).", ""]

        verdicts.append((model, cell))

    lines += ["## The registered predictions", "",
              "| # | Prediction | Observed | Met |", "| --- | --- | --- | --- |"]
    for model, cell in verdicts:
        d_blind = points(*cell[("blind", "frames")]) - points(*cell[("blind", "telemetry")])
        d_ctrl = points(*cell[("control", "frames")]) - points(*cell[("control", "telemetry")])
        ab = max(points(*cell[(c, "ab", a)]) for c in ("blind", "control") for a in ARMS)
        lines += [
            f"| Pr1 | blind detection rises by < {MARGIN} points ({model}) | {d_blind:+.0f} "
            f"points | {'yes' if d_blind < MARGIN else '**no**'} |",
            f"| Pr2 | control false alerts rise by < {MARGIN} points ({model}) | {d_ctrl:+.0f} "
            f"points | {'yes' if d_ctrl < MARGIN else '**no**'} |",
            f"| Pr3 | abstention stays ≤ 10% in both arms ({model}) | worst arm {ab:.0f}% | "
            f"{'yes' if ab <= 10 else '**no**'} |"]
    lines.append("")

    out = ROOT / "docs/results/vision_results.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    # The reading below the generated tables is written by hand; regenerating keeps it.
    kept = ""
    if out.exists() and "\n## Reading" in out.read_text():
        kept = out.read_text()[out.read_text().index("\n## Reading") + 1:]
    out.write_text("\n".join(lines) + "\n" + kept)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
