"""Score the system-state test against Pp1–Pp4 (docs/system_state_preregistration.md).

  ./.venv/bin/python scripts/score_system_state.py
"""
import glob
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "results/system_state"
MODELS = ("gemini-3.8-live", "claude-opus-5", "gpt-6-astra")
ARMS = ("V0", "V1", "V2")
ABSTAIN = {"UNKNOWN", "CANNOT_VERIFY"}
N_ITEMS = 38


def load(model, arm):
    return [json.loads(Path(f).read_text()) for f in glob.glob(str(OUT / model / arm / "*.json"))]


def frac(k, n):
    return f"{k}/{n}" if n else "—"


def main():
    lines = ["# Does a model abstain when the system says the evidence cannot settle it?", "",
             "Registered before any item ran: [system_state_preregistration.md]"
             "(../system_state_preregistration.md). Generated by `scripts/score_system_state.py`. "
             "The probe's 38 items: U 14 (only UNKNOWN supported), A 9 (of which 2 have a required "
             "sensor missing but the fault already visible), N 15.", "",
             "| Model | Arm | Answered | U → UNKNOWN | A + A-missing → ANOMALOUS | A-missing → ANOMALOUS | N → NORMAL | N → UNKNOWN |",
             "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    st = {}
    for m in MODELS:
        for a in ARMS:
            rs = load(m, a)
            if not rs:
                continue
            U = [r for r in rs if r["set"] == "U"]
            A = [r for r in rs if r["set"] == "A"]
            Am = [r for r in A if r["missing"]]
            N = [r for r in rs if r["set"] == "N"]
            s = {"n": len(rs), "u": sum(r["said"] in ABSTAIN for r in U), "nu": len(U),
                 "a": sum(r["said"] == "ANOMALOUS" for r in A), "na": len(A),
                 "am": sum(r["said"] == "ANOMALOUS" for r in Am), "nam": len(Am),
                 "nn": sum(r["said"] == "NORMAL" for r in N), "nun": sum(r["said"] in ABSTAIN for r in N),
                 "nN": len(N)}
            st[(m, a)] = s
            lines.append(f"| {m} | {a} | {s['n']}/{N_ITEMS} | **{frac(s['u'], s['nu'])}** | "
                         f"{frac(s['a'], s['na'])} | {frac(s['am'], s['nam'])} | "
                         f"{frac(s['nn'], s['nN'])} | {frac(s['nun'], s['nN'])} |")
    low = sorted({m for (m, a), s in st.items() if s["n"] / N_ITEMS < 0.9})
    lines.append("")
    if low:
        lines += [f"**Coverage below 90% for: {', '.join(low)}. By the registration these are not "
                  "read.**", ""]

    def g(m, a, k):
        return st.get((m, a), {}).get(k, 0)

    meet1 = [m for m in MODELS if g(m, "V1", "nu") and g(m, "V1", "u") / g(m, "V1", "nu") >= 0.5]
    lines += ["## The registered predictions", "",
              "| # | Prediction | Observed | Met |", "| --- | --- | --- | --- |",
              f"| Pp1 | V1: U abstention ≥ 50% for at least 2 of 3 models | "
              + ", ".join(f"{m} {g(m, 'V1', 'u')}/{g(m, 'V1', 'nu')}" for m in MODELS)
              + f" | {'yes' if len(meet1) >= 2 else '**no**'} |"]
    ok2 = all(g(m, "V0", "a") - g(m, "V1", "a") < 3 and g(m, "V1", "nun") - g(m, "V0", "nun") < 3
              for m in meet1)
    lines.append(f"| Pp2 | V1 costs fewer than 3 of 9 detections and adds fewer than 3 N abstentions, "
                 f"for models meeting Pp1 ({', '.join(meet1) or 'none'}) | "
                 + ", ".join(f"{m}: A {g(m, 'V0', 'a')}→{g(m, 'V1', 'a')}, N-UNKNOWN "
                             f"{g(m, 'V0', 'nun')}→{g(m, 'V1', 'nun')}" for m in meet1)
                 + f" | {'yes' if meet1 and ok2 else '**no**' if meet1 else '—'} |")
    ok3 = all(g(m, "V2", "u") >= g(m, "V1", "u") - 2 for m in MODELS)
    lines.append(f"| Pp3 | V2 within 2 items of V1 on U abstention, or higher | "
                 + ", ".join(f"{m} {g(m, 'V1', 'u')}→{g(m, 'V2', 'u')}" for m in MODELS)
                 + f" | {'yes' if ok3 else '**no**'} |")
    gm = "gemini-3.8-live"
    gr = g(gm, "V1", "u") / g(gm, "V1", "nu") if g(gm, "V1", "nu") else 0
    lines.append(f"| Pp4 | Gemini's V1 U abstention below 50% | {g(gm, 'V1', 'u')}/{g(gm, 'V1', 'nu')} | "
                 f"{'yes' if gr < 0.5 else '**no**'} |")
    lines.append("")

    out = ROOT / "docs/results/system_state_results.md"
    kept = ""
    if out.exists() and "\n## Reading" in out.read_text():
        kept = out.read_text()[out.read_text().index("\n## Reading") + 1:]
    out.write_text("\n".join(lines) + "\n" + kept)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
