"""Score the probes against the registered predictions and write docs/results/probe_results.md."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from livelab.probes import score  # noqa: E402

MODEL = sys.argv[1] if len(sys.argv) > 1 else "gemini-3.8-live"


def load(root=ROOT / "results" / "probes" / MODEL):
    results = {}
    for p in Path(root).glob("*/*.json"):
        d = json.loads(p.read_text())
        results.setdefault(d["variant"], {})[d["item_id"]] = d
    return results


def frac(t):
    return f"{t[0]}/{t[1]}" + (f" ({t[0] / t[1]:.0%})" if t[1] else "")


def covered(s, variant, sets="U", floor=0.9):
    """A measure is read only if nearly every registered item answered (deviation 7)."""
    cov = s.get(variant, {}).get("coverage", {})
    if isinstance(cov, tuple):
        cov = {"P1": cov}
    got = [cov[x] for x in sets if x in cov]
    return bool(got) and all(n and a / n >= floor for a, n in got)


def verdicts(s):
    r = lambda t: t[0] / t[1] if t[1] else float("nan")
    b0, b1, b2, b3 = (s.get(v, {}) for v in ("B0", "B1", "B2", "B3"))
    rows = []
    if covered(s, "P1", ("P1",)):
        ba = s["P1"]["detectable"]["balanced_accuracy"]
        rows.append(("Pr1", "P1 detectability balanced accuracy ≥ 80%", f"{ba:.0%}", ba >= 0.8))
    if b0 and covered(s, "B0"):
        rows.append(("Pr2", "B0 abstention on U ≤ 10%", frac(b0["abstention_on_U"]), r(b0["abstention_on_U"]) <= 0.10))
    if b1 and covered(s, "B1"):
        ok = r(b1["atmosphere_cannot_verify_on_U"]) >= 0.5 and r(b1["conflation_rate_on_U"]) >= 0.4
        rows.append(("Pr3", "B1: atmosphere cannot_verify on ≥ half of U, conflation ≥ 40%",
                     f"{frac(b1['atmosphere_cannot_verify_on_U'])}; conflation {frac(b1['conflation_rate_on_U'])}", ok))
    if b2 and covered(s, "B2", "UNA"):
        ok = r(b2["abstention_on_U"]) >= 0.5 and r(b2["over_abstention_on_N"]) <= 0.2 and r(b2["detection_on_A"]) >= 0.8
        rows.append(("Pr4", "B2 abstention on U ≥ 50%, N over-abstention ≤ 20%, A detection ≥ 80%",
                     f"U {frac(b2['abstention_on_U'])}; N {frac(b2['over_abstention_on_N'])}; A {frac(b2['detection_on_A'])}", ok))
    if b0 and b3 and covered(s, "B0") and covered(s, "B3"):
        d = abs(r(b3["abstention_on_U"]) - r(b0["abstention_on_U"]))
        rows.append(("Pr5", "B3 vs B0 abstention on U differs by < 20 points", f"{d:.0%} apart", d < 0.2))
    return rows


def main():
    items = json.load(open(ROOT / "data/probes/items.json"))
    loaded = load()
    s = score(items, loaded)
    lines = [f"# UNKNOWN probe results: {MODEL}", "",
             "Generated by `scripts/score_probes.py`. Design, predictions and reading rules:",
             "[probe_preregistration.md](../probe_preregistration.md). One run per item.", "",
             "| Variant | Abstention on U | Over-abstention on N | Detection on A |", "| --- | --- | --- | --- |"]
    sets = {i["item_id"]: i["set"] for i in items["in_context"]}
    tried = {(d["variant"], sets.get(d["item_id"])) for v in loaded.values() for d in v.values()}

    def cell(v, key, st):
        if (v, st) not in tried:
            return "not run"                      # the staged design, not a failure
        if not covered(s, v, st):
            return f"not read ({frac(s[v]['coverage'][st])} answered)"
        return frac(s[v][key])
    for v in ("B0", "B1", "B2", "B3"):
        if v in s and any((v, st) in tried for st in "UNA"):
            lines.append(f"| {v} | {cell(v, 'abstention_on_U', 'U')} | {cell(v, 'over_abstention_on_N', 'N')} "
                         f"| {cell(v, 'detection_on_A', 'A')} |")
    if "B1" in s and covered(s, "B1"):
        lines += ["", f"B1: atmosphere marked `cannot_verify` on U: {frac(s['B1']['atmosphere_cannot_verify_on_U'])}; "
                      f"conflation (cannot_verify and NORMAL): {frac(s['B1']['conflation_rate_on_U'])}; "
                      f"verifiability accuracy: {frac(s['B1']['verifiability_accuracy'])}."]
    if "P1" in s and covered(s, "P1", ("P1",)):
        for kind, m in ((k, m) for k, m in s["P1"].items() if k != "coverage"):
            lines.append(f"P1 {kind}: accuracy {frac(m['accuracy'])}, balanced {m['balanced_accuracy']:.0%}, "
                         f"by truth {m['by_truth']}.")
    cov = {v: s[v]["coverage"] for v in sorted(s) if s[v].get("coverage")}
    cov = {v: (c if isinstance(c, dict) else {"": c}) for v, c in cov.items()}
    thin = [f"{v}{' ' + x if x else ''} {frac(c)}" for v, cs in cov.items() for x, c in cs.items()
            if c[1] and c[0] < c[1] and (v, x or "P1") in tried | {(w, "P1") for w in ("P1",)}]
    if thin:
        lines += ["", "**Items with no answer are excluded from every rate above** (pre-registration, deviation 7): "
                      "silence can be the model declining or the API's function-call path failing, and the two are "
                      "indistinguishable from the client. Coverage (answered / registered): " + ", ".join(thin) + ". "
                      "A variant below 90% coverage is not read as a measurement."]
    lines += ["", "| # | Registered prediction | Observed | Met |", "| --- | --- | --- | --- |"]
    lines += [f"| {a} | {b} | {c} | {'yes' if d else 'no'} |" for a, b, c, d in verdicts(s)]
    out = ROOT / "docs/results" / ("probe_results.md" if MODEL == "gemini-3.8-live" else f"probe_results_{MODEL}.md")
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
