"""Score the undersampling study against its registered predictions.

  ./.venv/bin/python scripts/score_transients.py
"""
import glob
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from livelab.undersampling import CADENCES, GLIMPSED, MISSED, RESOLVED  # noqa: E402

ABSTAIN = {"UNKNOWN", "CANNOT_VERIFY"}


def load(model):
    rows = []
    for f in glob.glob(str(ROOT / "results/transients" / model / "*.json")):
        d = json.loads(Path(f).read_text())
        a = [c["args"] for c in d["calls"] if c["name"] == "report_assessment"]
        if a:
            rows.append(d | {"said": a[-1].get("execution_state")})
    return rows


def frac(hit, n):
    return f"{hit}/{n}" + (f" ({hit / n:.0%})" if n else "")


def main():
    models = sorted(p.name for p in (ROOT / "results/transients").glob("*") if p.is_dir()) \
        if (ROOT / "results/transients").exists() else []
    if not models:
        sys.exit("nothing to score yet: run scripts/run_transients.py first")

    lines = ["# Undersampling results: what a transient supports, and what the model says", "",
             "Registered before any run: [undersampling_preregistration.md]"
             "(../undersampling_preregistration.md). Generated by `scripts/score_transients.py`.",
             "One run per item; 12 transient episodes, each delivered at three cadences over the",
             "same 20-minute window.", ""]

    first = load(models[0])
    lines += ["## The ground truth, before any model is asked", "",
              "*Onsets and durations were chosen by hand so that every class is populated; the counts",
              "below describe these twelve episodes, not a rate.*", "",
              "| Cadence | Events per item | Missed | Glimpsed | Resolved |", "| --- | --- | --- | --- | --- |"]
    for c in CADENCES:
        at = [r for r in first if r["cadence_s"] == c]
        ev = at[0]["events"] if at else "—"
        lines.append(f"| {c} s | {ev} | " + " | ".join(
            str(sum(r["class"] == k for r in at)) for k in (MISSED, GLIMPSED, RESOLVED)) + " |")
    lines += ["", "Same twelve faults, same seeds. What the evidence can support is set by how often",
              "the instrument is read.", ""]

    for model in models:
        rows = load(model)
        lines += [f"## {model}", "",
                  "| Cadence | Detection (resolved -> ANOMALOUS) | Abstention (glimpsed -> UNKNOWN) | False alert (missed -> ANOMALOUS) |",
                  "| --- | --- | --- | --- |"]
        for c in CADENCES:
            at = [r for r in rows if r["cadence_s"] == c]
            res = [r for r in at if r["class"] == RESOLVED]
            gli = [r for r in at if r["class"] == GLIMPSED]
            mis = [r for r in at if r["class"] == MISSED]
            lines.append(
                f"| {c} s | {frac(sum(r['said'] == 'ANOMALOUS' for r in res), len(res))} "
                f"| {frac(sum(r['said'] in ABSTAIN for r in gli), len(gli))} "
                f"| {frac(sum(r['said'] == 'ANOMALOUS' for r in mis), len(mis))} |")
        tok = [(r["events"], (r.get("usage") or {}).get("prompt_token_count")) for r in rows]
        tok = [(e, t) for e, t in tok if t]
        if tok:
            per = {}
            for e, t in tok:
                per.setdefault(e, []).append(t)
            lines += ["", "Prompt tokens per item, by events delivered: " +
                      ", ".join(f"{e} events {sum(v) / len(v):,.0f}" for e, v in sorted(per.items())) + "."]
        lines.append("")

    lines += ["## The registered predictions", "",
              "| # | Prediction | Observed | Met |", "| --- | --- | --- | --- |"]
    for model in models:
        rows = load(model)
        fine = [r for r in rows if r["cadence_s"] == 5 and r["class"] == RESOLVED]
        det5 = sum(r["said"] == "ANOMALOUS" for r in fine)
        gli = [r for r in rows if r["class"] == GLIMPSED]
        ab = sum(r["said"] in ABSTAIN for r in gli)
        fa = {c: sum(r["said"] == "ANOMALOUS" for r in rows
                     if r["cadence_s"] == c and r["class"] == MISSED) for c in (5, 120)}
        per = {}
        for r in rows:
            t = (r.get("usage") or {}).get("prompt_token_count")
            if t:
                per.setdefault(r["events"], []).append(t)
        rate = {e: sum(v) / len(v) / e for e, v in sorted(per.items())}
        superlinear = len(rate) > 1 and list(rate.values())[-1] > list(rate.values())[0]
        lines += [
            f"| Pr1 | detection at 5 s \u2265 80% ({model}) | {frac(det5, len(fine))} | "
            f"{'yes' if len(fine) and det5 / len(fine) >= 0.8 else '**no**'} |",
            f"| Pr2 | abstention on glimpsed \u2264 10% ({model}) | {frac(ab, len(gli))} | "
            f"{'yes' if not len(gli) or ab / len(gli) <= 0.1 else '**no**'} |",
            f"| Pr3 | false alerts at 5 s \u2264 2\u00d7 those at 120 s ({model}) | "
            f"{fa[5]} vs {fa[120]} | {'yes' if fa[5] <= 2 * fa[120] else '**no**'} |",
            f"| Pr4 | tokens per event rise with event count ({model}) | "
            + (", ".join(f"{e} events {r:.0f}/event" for e, r in rate.items()) if rate else "not recorded")
            + f" | {'yes' if superlinear else '**no**' if rate else '—'} |"]
    lines.append("")

    out = ROOT / "docs/results/undersampling_results.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    # The section below the generated tables is written by hand; regenerating keeps it.
    kept = ""
    if out.exists() and "\n## What this settles" in out.read_text():
        kept = out.read_text()[out.read_text().index("\n## What this settles") + 1:]
    out.write_text("\n".join(lines) + "\n" + kept)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
