"""Score the follow-up (docs/vision_followup_preregistration.md) against Pf1–Pf3.

Written before either new arm ran, including the keyword list for mismatch mentions.

  ./.venv/bin/python scripts/score_vision_followup.py [--model claude-opus-5]
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from scripts.score_vision import ABSTAIN, COVERAGE, load, pct, points  # noqa: E402

ARMS = ("telemetry", "frames", "sentence", "other_frames")
NEW = ("sentence", "other_frames")
# The sentence arm says photographs are attached when none are. An answer that notices counts here.
MISMATCH = re.compile(
    r"(no|not|missing|absent|without|none of the)\s+(\w+\s+){0,3}(photo|image|picture|frame)s?"
    r"|(photo|image|picture|frame)s?\s+(\w+\s+){0,4}(not|missing|absent|unavailable|were not|was not)"
    r"|not\s+(been\s+)?(attached|provided|included|visible|received)", re.I)


def mentions_mismatch(record):
    text = json.dumps(record["calls"], ensure_ascii=False) + " " + str(record.get("spoken") or "")
    return bool(MISMATCH.search(text))


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="claude-opus-5")
    args = ap.parse_args(argv)
    registered = {it["item_id"]: it
                  for it in json.load(open(ROOT / "data/vision/items.json"))["items"]}
    arms = {a: {i: r for i, r in load(args.model, a).items() if i in registered} for a in ARMS}
    paired = sorted(set.intersection(*(set(arms[a]) for a in ARMS)))

    lines = [f"# The follow-up: what moved {args.model}?", "",
             "> **Correction (2026-09-21).** Every item here was sent with a wrong plant description "
             "(five heater temperatures described as column temperatures; [deviation 5](../realdata_preregistration.md)). "
             "Each false alert on a fault-free run cites one of those heaters, `T701`. "
             "The arms all received the same description, so the comparisons between arms "
             "hold. In the [real-plant rerun](realdata_v2_results.md) with the description "
             "corrected, Opus still alerted on that heater in 13 of 13 false alerts, so the "
             "wrong description does not explain the reading it doubts. The camera studies "
             "were not rerun.", "",
             "Registered before either new arm ran: "
             "[vision_followup_preregistration.md](../vision_followup_preregistration.md). "
             "Generated by `scripts/score_vision_followup.py`, written before the run.", "",
             "| Arm | Announced | Attached | Answered | Coverage |",
             "| --- | --- | --- | --- | --- |"]
    what = {"telemetry": ("no", "nothing"), "frames": ("yes", "this run's frames"),
            "sentence": ("yes", "nothing"), "other_frames": ("yes", "a different normal run's frames")}
    for a in ARMS:
        n = len(arms[a])
        lines.append(f"| {a} | {what[a][0]} | {what[a][1]} | {n}/{len(registered)} | "
                     f"{n / len(registered):.0%} |")
    under = [a for a in ARMS if len(arms[a]) / len(registered) < COVERAGE]
    lines += ["", f"**{len(paired)} items answered in all four arms**; everything below is scored "
                  "on those.", ""]
    if under:
        lines += [f"**Coverage below {COVERAGE:.0%} in: {', '.join(under)}. By the registration "
                  "this is not read.**", ""]

    rate, ab = {}, {}
    for cond in ("blind", "control"):
        ids = [i for i in paired if registered[i]["condition"] == cond]
        for a in ARMS:
            rate[(cond, a)] = (sum(arms[a][i]["said"] == "ANOMALOUS" for i in ids), len(ids))
            ab[(cond, a)] = (sum(arms[a][i]["said"] in ABSTAIN for i in ids), len(ids))

    def shift(cond, a):
        return points(*rate[(cond, a)]) - points(*rate[(cond, "telemetry")])

    lines += ["| Answered `ANOMALOUS` | " + " | ".join(ARMS) + " |",
              "| --- |" + " --- |" * len(ARMS)]
    for cond in ("blind", "control"):
        lines.append(f"| {cond} | " + " | ".join(pct(*rate[(cond, a)]) for a in ARMS) + " |")
    lines += ["", "| Shift from telemetry, points | " + " | ".join(ARMS[1:]) + " |",
              "| --- |" + " --- |" * (len(ARMS) - 1)]
    for cond in ("blind", "control"):
        lines.append(f"| {cond} | " + " | ".join(f"{shift(cond, a):+.0f}" for a in ARMS[1:]) + " |")
    lines += ["", "| Abstention | " + " | ".join(ARMS) + " |", "| --- |" + " --- |" * len(ARMS)]
    for cond in ("blind", "control"):
        lines.append(f"| {cond} | " + " | ".join(pct(*ab[(cond, a)]) for a in ARMS) + " |")

    mism = sum(mentions_mismatch(arms["sentence"][i]) for i in paired)
    lines += ["", f"**Mismatch mentions in the sentence arm:** {pct(mism, len(paired))} of answers "
                  "say the announced photographs are missing or not visible "
                  "(keyword list fixed in the scorer before the run).", ""]

    half = shift("control", "frames") / 2
    s_ctrl, o_ctrl, f_ctrl = (shift("control", a) for a in ("sentence", "other_frames", "frames"))
    worst = max(points(*ab[(c, a)]) for c in ("blind", "control") for a in NEW)
    lines += ["## The registered predictions", "",
              "| # | Prediction | Observed | Met |", "| --- | --- | --- | --- |",
              f"| Pf1 | sentence arm's control shift is under half the frames arm's "
              f"({half:+.0f}) | {s_ctrl:+.0f} | {'yes' if s_ctrl < half else '**no**'} |",
              f"| Pf2 | other_frames arm's control shift within 10 points of the frames arm's "
              f"({f_ctrl:+.0f}) | {o_ctrl:+.0f} | "
              f"{'yes' if abs(o_ctrl - f_ctrl) <= 10 else '**no**'} |",
              f"| Pf3 | abstention ≤ 10% in both new arms | worst {worst:.0f}% | "
              f"{'yes' if worst <= 10 else '**no**'} |", ""]
    if mism > len(paired) / 4:
        lines += ["**The sentence arm is not read as a clean test of the wording**: more than a "
                  "quarter of its answers notice that no photographs arrived, which the "
                  "registration fixed as the bar.", ""]

    out = ROOT / "docs/results/vision_followup_results.md"
    # The reading below the generated tables is written by hand; regenerating keeps it.
    kept = ""
    if out.exists() and "\n## Reading" in out.read_text():
        kept = out.read_text()[out.read_text().index("\n## Reading") + 1:]
    out.write_text("\n".join(lines) + "\n" + kept)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
